#!/usr/bin/env bash

if [[ "$DOCKER_ENV" == "local" || "$DOCKER_ENV" == "testing" ]]; then
    mkdir -p "$PROJECT_ROOT/data"

    # Init .env file
    if [[ ! -f "$PROJECT_ROOT/.env" && -f "$PROJECT_ROOT/.env.example" ]]; then
        cp -a "$PROJECT_ROOT/.env.example" "$PROJECT_ROOT/.env"
    fi

    export DEV_MODE="yes"
    export DOCKER_BUILDKIT=1

    # Load data from images registered in docker-helper.yml
    source <(dhelper_yaml | grep "^DHELPER_images_" | sed -E "s/^(.*)$/export \1/g")

    eval "SOURCE_IMAGE=\${DHELPER_images_${HSTC_DEFAULT_IMAGE:-stable}_source_image:?}"
    eval "IMAGE_VERSION=\${DHELPER_images_${HSTC_DEFAULT_IMAGE:-stable}_version:?}"
    if [[ "$SOURCE_IMAGE" =~ : ]]; then
        export HESTIACP_IMAGE="$SOURCE_IMAGE-$IMAGE_VERSION"
    else
        export HESTIACP_IMAGE="$SOURCE_IMAGE:$IMAGE_VERSION"
    fi
fi
