#!/usr/bin/env bash

# Run "docker-compose up" with a different image than the default

if [[ ! "$1" || "${1,,}" == "help" || "${1,,}" == "--help" || "${1,,}" == "-h" ]]; then
    echo "image-up <image> [<run-rm>]"
    exit 0
fi

IMAGE_NAME="${1:-${HSTC_DEFAULT_IMAGE:-stable}}" # The image that will be used
run_rm="$2" # Remove existing containers before starting

# Load data from images registered in docker-helper.yml
source <(dhelper_yaml | grep "^DHELPER_images_" | sed -E "s/^(.*)$/export \1/g")

eval "SOURCE_IMAGE=\${DHELPER_images_${IMAGE_NAME}_source_image:?}"
eval "IMAGE_VERSION=\${DHELPER_images_${IMAGE_NAME}_version:?}"
if [[ "$SOURCE_IMAGE" =~ : ]]; then
    export HESTIACP_IMAGE="$SOURCE_IMAGE-$IMAGE_VERSION"
else
    export HESTIACP_IMAGE="$SOURCE_IMAGE:$IMAGE_VERSION"
fi

if [[ "${run_rm,,}" == "yes" ]]; then
    docker-compose rm -sf
fi

if [[ -z "$(docker images -q "$HESTIACP_IMAGE" 2> /dev/null)" ]]; then
    echo "Failed to start containers. Image \"$HESTIACP_IMAGE\" not found."
    exit 1
fi

docker-compose up
#docker-compose up --force-recreate
